/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubpagesRouteImport } from './routes/_subpages'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubpagesResumeRouteImport } from './routes/_subpages/resume'
import { Route as SubpagesProjectsRouteImport } from './routes/_subpages/projects'
import { Route as SubpagesContactRouteImport } from './routes/_subpages/contact'
import { Route as SubpagesAboutRouteImport } from './routes/_subpages/about'

const SubpagesRoute = SubpagesRouteImport.update({
  id: '/_subpages',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubpagesResumeRoute = SubpagesResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => SubpagesRoute,
} as any)
const SubpagesProjectsRoute = SubpagesProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => SubpagesRoute,
} as any)
const SubpagesContactRoute = SubpagesContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SubpagesRoute,
} as any)
const SubpagesAboutRoute = SubpagesAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SubpagesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof SubpagesAboutRoute
  '/contact': typeof SubpagesContactRoute
  '/projects': typeof SubpagesProjectsRoute
  '/resume': typeof SubpagesResumeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof SubpagesAboutRoute
  '/contact': typeof SubpagesContactRoute
  '/projects': typeof SubpagesProjectsRoute
  '/resume': typeof SubpagesResumeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_subpages': typeof SubpagesRouteWithChildren
  '/_subpages/about': typeof SubpagesAboutRoute
  '/_subpages/contact': typeof SubpagesContactRoute
  '/_subpages/projects': typeof SubpagesProjectsRoute
  '/_subpages/resume': typeof SubpagesResumeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/contact' | '/projects' | '/resume'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/contact' | '/projects' | '/resume'
  id:
    | '__root__'
    | '/'
    | '/_subpages'
    | '/_subpages/about'
    | '/_subpages/contact'
    | '/_subpages/projects'
    | '/_subpages/resume'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SubpagesRoute: typeof SubpagesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_subpages': {
      id: '/_subpages'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SubpagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_subpages/resume': {
      id: '/_subpages/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof SubpagesResumeRouteImport
      parentRoute: typeof SubpagesRoute
    }
    '/_subpages/projects': {
      id: '/_subpages/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof SubpagesProjectsRouteImport
      parentRoute: typeof SubpagesRoute
    }
    '/_subpages/contact': {
      id: '/_subpages/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SubpagesContactRouteImport
      parentRoute: typeof SubpagesRoute
    }
    '/_subpages/about': {
      id: '/_subpages/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SubpagesAboutRouteImport
      parentRoute: typeof SubpagesRoute
    }
  }
}

interface SubpagesRouteChildren {
  SubpagesAboutRoute: typeof SubpagesAboutRoute
  SubpagesContactRoute: typeof SubpagesContactRoute
  SubpagesProjectsRoute: typeof SubpagesProjectsRoute
  SubpagesResumeRoute: typeof SubpagesResumeRoute
}

const SubpagesRouteChildren: SubpagesRouteChildren = {
  SubpagesAboutRoute: SubpagesAboutRoute,
  SubpagesContactRoute: SubpagesContactRoute,
  SubpagesProjectsRoute: SubpagesProjectsRoute,
  SubpagesResumeRoute: SubpagesResumeRoute,
}

const SubpagesRouteWithChildren = SubpagesRoute._addFileChildren(
  SubpagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SubpagesRoute: SubpagesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
